# Generated by Django 5.0.6 on 2025-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='token_generated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
