# Generated by Django 5.0.6 on 2025-03-23 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('retired', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.AddField(
            model_name='credentials',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='token_generated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
                ('owner', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='src.boards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.users')),
            ],
            options={
                'db_table': 'collaborators',
            },
        ),
    ]
