# Generated by Django 5.0.6 on 2025-03-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_boards_credentials_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborators',
            name='accepted',
        ),
    ]
