# Generated by Django 5.0.6 on 2025-03-22 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_credentials_token_credentials_token_generated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
